apiVersion: nmstate.io/v1
kind: NodeNetworkConfigurationPolicy
metadata:
  annotations:
    description: a bond for vm traffics and vlans
  name: bond1-ktbdwhwknd01
spec:
  nodeSelector:
    kubernetes.io/hostname: ktbdwhwknd01.cmsnonprd.vayuktbcs
  desiredState:
    interfaces:
      - name: bond1
        type: bond
        state: up
        mtu: 9000
        link-aggregation:
          mode: 802.3ad
          ports:
            - ens4f1
            - ens5f1
      - name: ens4f1
        type: ethernet
        state: up
        mtu: 9000
        ipv4:
          enabled: false
        ipv6:
          enabled: false
      - name: ens5f1
        type: ethernet
        state: up
        mtu: 9000
        ipv4:
          enabled: false
        ipv6:
          enabled: false
